AWSTemplateFormatVersion: 2010-09-09
Description: >
 Kittens Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.

Resources:
  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: Firstkey 
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value:  !Sub Web Server ${AWS::StackName}
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 /var/www/html
          cd /var/www/html
          wget https://raw.githubusercontent.com/serhat-project/my-projects/main/python/hands-on/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/serhat-project/my-projects/main/python/hands-on/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/serhat-project/my-projects/main/python/hands-on/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/serhat-project/my-projects/main/python/hands-on/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/serhat-project/my-projects/main/python/hands-on/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png

     

            
            
           
            
